version: "3.8"
services:
  api:
    image: security/api:0.0.1-SNAPSHOT
    ports:
      - "7878:7878"
    volumes:
      - /home/obed/Documents/Example/audit-rest-api/src/main/resources/application.properties:/opt/backend/API/bin/conf/application.properties
      - /home/obed/Documents/Example/audit-rest-api/src/main/resources/logback.xml:/opt/backend/API/conf/logback.xm
    networks:
      - app_net
    restart: always