server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Managua
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: America/Managua

